"""Explicit observed-layout registry. Unknown payloads are never guessed.

Field names for the energy profile follow vendor Parquet exports. They describe
instrument channels, not independently verified field wiring or clock accuracy.
"""
from dataclasses import dataclass

PROFILE = "observed-fel-0bba1400"

@dataclass(frozen=True)
class Layout:
    tag: int
    size: int
    group: str
    fields: tuple[str, ...] = ()
    period_field: str | None = None
    profile: str = PROFILE

ENERGY_TREND_FIELDS = (
    'voltage_rms_an_min',
    'voltage_rms_an_max',
    'voltage_rms_an_avg',
    'voltage_rms_bn_min',
    'voltage_rms_bn_max',
    'voltage_rms_bn_avg',
    'voltage_rms_cn_min',
    'voltage_rms_cn_max',
    'voltage_rms_cn_avg',
    'voltage_rms_ab_min',
    'voltage_rms_ab_max',
    'voltage_rms_ab_avg',
    'voltage_rms_bc_min',
    'voltage_rms_bc_max',
    'voltage_rms_bc_avg',
    'voltage_rms_ca_min',
    'voltage_rms_ca_max',
    'voltage_rms_ca_avg',
    'current_rms_a_min',
    'current_rms_a_max',
    'current_rms_a_avg',
    'current_rms_b_min',
    'current_rms_b_max',
    'current_rms_b_avg',
    'current_rms_c_min',
    'current_rms_c_max',
    'current_rms_c_avg',
    'voltage_thd_a_min',
    'voltage_thd_a_max',
    'voltage_thd_a_avg',
    'voltage_thd_b_min',
    'voltage_thd_b_max',
    'voltage_thd_b_avg',
    'voltage_thd_c_min',
    'voltage_thd_c_max',
    'voltage_thd_c_avg',
    'current_thd_a_min',
    'current_thd_a_max',
    'current_thd_a_avg',
    'current_thd_b_min',
    'current_thd_b_max',
    'current_thd_b_avg',
    'current_thd_c_min',
    'current_thd_c_max',
    'current_thd_c_avg',
    'frequency_min',
    'frequency_max',
    'frequency_avg',
    'power_rms_active_a_min',
    'power_rms_active_a_max',
    'power_rms_active_a_avg',
    'power_rms_active_b_min',
    'power_rms_active_b_max',
    'power_rms_active_b_avg',
    'power_rms_active_c_min',
    'power_rms_active_c_max',
    'power_rms_active_c_avg',
    'power_rms_active_total_min',
    'power_rms_active_total_max',
    'power_rms_active_total_avg',
    'power_rms_apparent_a_min',
    'power_rms_apparent_a_max',
    'power_rms_apparent_a_avg',
    'power_rms_apparent_b_min',
    'power_rms_apparent_b_max',
    'power_rms_apparent_b_avg',
    'power_rms_apparent_c_min',
    'power_rms_apparent_c_max',
    'power_rms_apparent_c_avg',
    'power_rms_apparent_total_min',
    'power_rms_apparent_total_max',
    'power_rms_apparent_total_avg',
    'power_rms_nonactive_a_min',
    'power_rms_nonactive_a_max',
    'power_rms_nonactive_a_avg',
    'power_rms_nonactive_b_min',
    'power_rms_nonactive_b_max',
    'power_rms_nonactive_b_avg',
    'power_rms_nonactive_c_min',
    'power_rms_nonactive_c_max',
    'power_rms_nonactive_c_avg',
    'power_rms_nonactive_total_min',
    'power_rms_nonactive_total_max',
    'power_rms_nonactive_total_avg',
    'power_fund_active_a_min',
    'power_fund_active_a_max',
    'power_fund_active_a_avg',
    'power_fund_active_b_min',
    'power_fund_active_b_max',
    'power_fund_active_b_avg',
    'power_fund_active_c_min',
    'power_fund_active_c_max',
    'power_fund_active_c_avg',
    'power_fund_active_total_min',
    'power_fund_active_total_max',
    'power_fund_active_total_avg',
    'power_fund_apparent_a_min',
    'power_fund_apparent_a_max',
    'power_fund_apparent_a_avg',
    'power_fund_apparent_b_min',
    'power_fund_apparent_b_max',
    'power_fund_apparent_b_avg',
    'power_fund_apparent_c_min',
    'power_fund_apparent_c_max',
    'power_fund_apparent_c_avg',
    'power_fund_apparent_total_min',
    'power_fund_apparent_total_max',
    'power_fund_apparent_total_avg',
    'power_fund_nonactive_a_min',
    'power_fund_nonactive_a_max',
    'power_fund_nonactive_a_avg',
    'power_fund_nonactive_b_min',
    'power_fund_nonactive_b_max',
    'power_fund_nonactive_b_avg',
    'power_fund_nonactive_c_min',
    'power_fund_nonactive_c_max',
    'power_fund_nonactive_c_avg',
    'power_fund_nonactive_total_min',
    'power_fund_nonactive_total_max',
    'power_fund_nonactive_total_avg',
    'powfac_pf_a_min',
    'powfac_pf_a_max',
    'powfac_pf_a_avg',
    'powfac_pf_b_min',
    'powfac_pf_b_max',
    'powfac_pf_b_avg',
    'powfac_pf_c_min',
    'powfac_pf_c_max',
    'powfac_pf_c_avg',
    'powfac_pf_total_min',
    'powfac_pf_total_max',
    'powfac_pf_total_avg',
    'powfac_dpf_a_min',
    'powfac_dpf_a_max',
    'powfac_dpf_a_avg',
    'powfac_dpf_b_min',
    'powfac_dpf_b_max',
    'powfac_dpf_b_avg',
    'powfac_dpf_c_min',
    'powfac_dpf_c_max',
    'powfac_dpf_c_avg',
    'powfac_dpf_total_min',
    'powfac_dpf_total_max',
    'powfac_dpf_total_avg',
    'energy_active_a',
    'energy_active_b',
    'energy_active_c',
    'energy_active_total',
    'energy_apparent_a',
    'energy_apparent_b',
    'energy_apparent_c',
    'energy_apparent_total',
    'energy_nonactive_a',
    'energy_nonactive_b',
    'energy_nonactive_c',
    'energy_nonactive_total',
    'energy_consumed_total',
    'energy_supplied_total',
    'aux1_min',
    'aux1_max',
    'aux1_avg',
    'aux2_min',
    'aux2_max',
    'aux2_avg',
    'current_rms_n_min',
    'current_rms_n_max',
    'current_rms_n_avg',
    'voltage_symm_comp_negative',
    'voltage_symm_comp_positive',
    'voltage_symm_comp_zero',
    'voltage_effective',
    'current_effective',
    'voltage_fund_an',
    'voltage_fund_bn',
    'voltage_fund_cn',
    'current_fund_a',
    'current_fund_b',
    'current_fund_c',
    'voltage_fund_effective',
    'current_fund_effective',
)

DEMAND_FIELDS = (
    'voltage_rms_an',
    'voltage_rms_bn',
    'voltage_rms_cn',
    'current_rms_a',
    'current_rms_b',
    'current_rms_c',
    'energy_active_a',
    'energy_active_b',
    'energy_active_c',
    'energy_active_total',
    'energy_apparent_a',
    'energy_apparent_b',
    'energy_apparent_c',
    'energy_apparent_total',
    'energy_nonactive_a',
    'energy_nonactive_b',
    'energy_nonactive_c',
    'energy_nonactive_total',
    'energy_consumed_total',
    'energy_supplied_total',
)

LAYOUTS = (
    Layout(105, 5208, "waveforms"),
    Layout(111, 104, "events"),
    Layout(112, 32064, "transients"),
    Layout(119, 1724, "trends"),
    Layout(70, 744, "energy_trends", ENERGY_TREND_FIELDS, "trend_period"),
    Layout(71, 104, "demand", DEMAND_FIELDS, "demand_period"),
)
LAYOUT_REGISTRY = {(layout.profile, layout.tag, layout.size): layout for layout in LAYOUTS}

def resolve_layout(tag: int, size: int, profile: str = PROFILE):
    """Return only an exact registered match, never infer a layout from size alone."""
    return LAYOUT_REGISTRY.get((profile, tag, size))

def field_unit(name: str):
    """Known stored engineering units; None means not asserted by this decoder."""
    if name.startswith("current_rms_"): return "A"
    if name.startswith("voltage_rms_"): return "V"
    if name.startswith("power_rms_active_"): return "W"
    if name.startswith("power_rms_apparent_"): return "VA"
    if name.startswith("frequency_"): return "Hz"
    return None

def layout_inventory(records):
    """Inventory by tag AND size so unsupported variants remain visible."""
    from collections import Counter
    counts = Counter((r.tag, r.size) for r in records)
    return [
        {"tag": tag, "size": size, "count": count,
         "group": layout.group if (layout := resolve_layout(tag, size)) else None,
         "status": "supported" if layout else "uninterpreted"}
        for (tag, size), count in sorted(counts.items())
    ]
